version: "2.4"

services:
  penguin-localdb:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: penguin-localdb
    shm_size: 1gb
    ports:
      - "15432:5432"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql
    command: --backup-source prod

volumes:
  postgres:
